### ISSUE TITLE
New release version and tag in the repo

### ISSUE THREAD

**Issue by jsedlace** [xt0rted/block-autosquash-commits-action#72]
Hey @xt0rted , would it be possible to release new version and tag the repo, so we don't need to use @master, which may change possibly every day?

**Comment by xt0rted** [comment]
There's a [v2.0.0](https://github.com/xt0rted/block-autosquash-commits-action/releases/tag/v2.0.0) release that you can use. I forgot to update the readme when I did that, it's a hold over from the original actions preview that recommended you use `@master` instead of tags/releases.

**Comment by xt0rted** [comment]
I just created a `v2` tag as well.
